# Generated by Django 6.0.3 on 2026-03-24 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_todo_app', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plan_todo_app.list'),
            preserve_default=False,
        ),
    ]
